### ISSUE TITLE
able to use Spanish bibles without needing to put an accent

### ISSUE THREAD

**Issue by Obadiahcruz** [caleb531/youversion-suggest-alfred#14]
I love to type the books of the Bible in Spanish without needing to write accents. it is extremely tiresome to learn where the accents go when wanting to type fast. thank you for this amazing amazing workflow! is there a way to make this happen? 

thanks in advance !

**Comment by caleb531** [comment]
@Obadiahcruz You can do it yourself in about 15 minutes. As for an automatic solution, I need to think about the right way to go about it. Because in many languages, accents or non-latin characters can change the meaning entirely.

Here's the manual steps you can take:

1. Open **Alfred Preferences**
2. Navigate to the **Workflows** section of Alfred Preferences
3. Right-click on the **YouVersion Suggest** workflow, and choose **Open in FInder** from the right-click menu
4. Navigate into the **yvs/data/bible/** folder, and open **bible-spa.json** in your favorite text/code editor
5. You'll see all the Spanish names of the Bible books; edit them as you please, and save the file when you're done!

The tedious part will be doing this for every book of the Bible. But you can probably leverage your editor's Find And Replace function to speed up the process.
