### ISSUE TITLE
"yvfilter + bible reference" does Google search (macOS Ventura)

### ISSUE THREAD

**Issue by pauliwallnuts** [caleb531/youversion-suggest-alfred#21]
Hey, upgraded to Ventura and yvfilter stopped sending me to bible.com but instead does a Google search. I'm using macOS 13.0 and Alfred 5.0.4 [2095]. Thanks!

<img width="605" alt="Screenshot 2022-11-03 at 9 53 04 AM" src="https://user-images.githubusercontent.com/117373823/199754738-0d7626b0-08e3-4359-af36-21c6cd2609e9.png">
<img width="605" alt="Screenshot 2022-11-03 at 9 53 18 AM" src="https://user-images.githubusercontent.com/117373823/199754762-f36b722a-dbb0-47be-9a4e-661899886604.png">

**Comment by caleb531** [comment]
@pauliwallnuts It's because Apple's Command Line Tools need to be updated. Open a Terminal and run the following command:

```
xcode-select --install
```

It will prompt you to download and install the Command Line Tools for Ventura. Once it's finished downloading and installing, you should be set. No restart should be required, either.

**Comment by pauliwallnuts** [comment]
Solved, thanks!
