### ISSUE TITLE
Error when previewing using shift key

### ISSUE THREAD

**Issue by Vaughn44** [caleb531/youversion-suggest-alfred#28]
I used to be able to preview a passage using the shift key, but this no longer works for me. Whenever I try, I get a blank preview window that says "Application error: a client-side exception has occurred (see the browser console for more information)."

Not sure if it stopped working when I updated Alfred, the workflow, or if something changed in Safari that could affect it.

I'm using version 14.1.5 of the workflow by the way. 

Thanks!

**Comment by caleb531** [comment]
@Vaughn44 It's not Alfred or the workflow itself, per se —it's because the Quick Look rendering engine for web pages (which is a lightweight Safari renderer) can't render the recently-revamped YouVersion website and all of the JavaScript it loads on the page.

I experience the issue too, and it is indeed annoying. Unfortunately, it's not something I can solve. Either Apple has to fix Quick Look, or YouVersion has to fix their website.

**Comment by Vaughn44** [comment]
Thanks Caleb for the quick response. I appreciate it!
